from __future__ import annotations

from threebody.experiments import TheoremSuite


def test_theorem_suite_reports_candidates_and_benchmarks() -> None:
    result = TheoremSuite().run()
    summary = result.as_dict()

    assert summary["theorem_candidates"]
    assert summary["benchmarks"]
    assert any(candidate["proven"] is False for candidate in summary["theorem_candidates"])
    assert any(candidate["name"] == "Impulse-Exchange Hierarchy Boundary Conjecture" for candidate in summary["theorem_candidates"])
    assert any(candidate["name"] == "Split Branch Explanation Conjecture" for candidate in summary["theorem_candidates"])
    assert any(benchmark["name"] == "low_crossing_scattering_map_score" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "levi_civita_collision_chart_certificate" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "levi_civita_regularized_rhs_certificate" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "levi_civita_non_synthetic_residual" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "levi_civita_residual_grid" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "levi_civita_local_equivalence" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "levi_civita_near_collision_scaling" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "levi_civita_normalized_residual_slope" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "levi_civita_tidal_perturbation_scaling" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "levi_civita_tidal_constant_bound" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "levi_civita_tidal_lipschitz_bound" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "figure_eight_center_of_mass_reduction" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "figure_eight_variational_linear_stability" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "figure_eight_variational_symplectic_residual" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "figure_eight_hamiltonian_jacobian_structure" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "figure_eight_choreography_symmetry" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "figure_eight_variational_step_convergence" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "low_crossing_scattering_map_selection" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "best_low_crossing_model_validation" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "best_hysteresis_width_model_validation" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "transition_word_stability" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "transition_word_nontriviality" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "transition_word_validation_diversity" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "refined_transition_word_stability" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "refined_transition_word_validation_diversity" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "return_word_stability" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "return_word_validation_diversity" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "high_crossing_grammar_outcome_validation" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "hysteresis_width_grammar_outcome_validation" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "grammar_branch_training_signal" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "grammar_branch_validation_support" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "grammar_branch_artifact_pass_rate" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "grammar_branch_artifact_min_score" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "grammar_branch_certified_accuracy" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "grammar_branch_mean_margin" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "grammar_branch_artifact_certified_accuracy" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "grammar_branch_artifact_mean_margin" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "grammar_branch_negative_control_gap" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "grammar_branch_artifact_negative_control_gap" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "high_crossing_grammar_negative_control_gap" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "hysteresis_width_grammar_negative_control_gap" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "high_crossing_grammar_artifact_negative_control_gap" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "hysteresis_width_grammar_artifact_negative_control_gap" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "high_crossing_selected_branch_score" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "hysteresis_width_selected_branch_score" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "high_crossing_selected_branch_is_feature" for benchmark in summary["benchmarks"])
    assert any(benchmark["name"] == "hysteresis_width_selected_branch_is_grammar" for benchmark in summary["benchmarks"])
